[workspace]
members = ["crates/lib/*"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
vlog = {path = "crates/lib/vlog"}

chrono = "0.4"
tracing = "0.1"

serde_json = "1.0"